### ISSUE TITLE
В блоке contacts все внутренние элементы должны именоваться от него

### ISSUE THREAD

**Issue by igosheva** [Yonmay/Yonmay.github.io#10]
https://github.com/Yonmay/Yonmay.github.io/blob/89ed0f6bb03e5d8648dcce2604f1ab271088c0be/index.html#L111

**Comment by igosheva** [comment]
Если ты создаешь самостоятельный блок contacts, то тогда все внутренние элементы должны именоваться уже от него, а не от footer, иначе зачем было тогда именовать его так.

**Comment by Yonmay** [comment]
так футер будет наверное получше
