### ISSUE TITLE
Никакой фиксированной высоты и ширины для текста!

### ISSUE THREAD

**Issue by igosheva** [Yonmay/Yonmay.github.io#11]
https://github.com/Yonmay/Yonmay.github.io/blob/89ed0f6bb03e5d8648dcce2604f1ab271088c0be/index.html#L47

**Comment by Yonmay** [comment]
тут вопрос в данном случае или всегда нельзя задавать высоту и ширину?
сделал так

> .services__name{
> 	font-size: 49px;
> 	font-family: 'Roboto';
> 	font-weight: bold;
> }

**Comment by igosheva** [comment]
Фиксированную высоту очень редко задают и только в том случае, когда это действительно нужно. на счет ширины - зависит от макета. Если делаешь адаптивный макет - тогда точно нет. Если дисктоп - то тоже в целом можно и без этого обойтись, если просто задать максимальную ширину например или задать ширину не тексту, а ее обертке. Как то так.
