### ISSUE TITLE
Сделай этот элемент ссылкой, чтобы пользователь имел возможность позвонить с твоего сайта. И поставь href="tel:8(800)00-392-10"

### ISSUE THREAD

**Issue by igosheva** [Yonmay/Yonmay.github.io#2]
https://github.com/Yonmay/Yonmay.github.io/blob/89ed0f6bb03e5d8648dcce2604f1ab271088c0be/index.html#L14

**Comment by Yonmay** [comment]
`<a href="8(800)00-392-10" class="phone">8(800)00-392-10</a>`
