### ISSUE TITLE
Внутри весь контент должен оборачивать container с шириной 1100px

### ISSUE THREAD

**Issue by igosheva** [Yonmay/Yonmay.github.io#3]
https://github.com/Yonmay/Yonmay.github.io/blob/89ed0f6bb03e5d8648dcce2604f1ab271088c0be/index.html#L11

**Comment by igosheva** [comment]
Посмотри внимательно домашку и ты увидишь, что внутренность всех больших блоков (шапку, контент, футер) оборачивает container

**Comment by Yonmay** [comment]
как я понял отдельно хедер, осн. контент и футер заключены в 3 контейнера сделал так              
`<div class="container">`  с общим свойством

>  .container{
> 	width: 1100px;
> }
