### ISSUE TITLE
Нужна общая обертка

### ISSUE THREAD

**Issue by igosheva** [Yonmay/Yonmay.github.io#4]
https://github.com/Yonmay/Yonmay.github.io/blob/89ed0f6bb03e5d8648dcce2604f1ab271088c0be/index.html#L18

**Comment by igosheva** [comment]
Блоки sidebar и services лежат в одном большом связующем блоке, соответственно тебе нужно их положить в один блок и обернуть в container, для того, чтобы в дальнейшем они центрировались.

**Comment by Yonmay** [comment]
я так понял этот вопрос вытек из обертки в контейнер с шириной 1100 и решился тем что я обернул в 3 разных футер, осн. контент, хедер.
И как-то сам собой решился))
