### ISSUE TITLE
Нейминг не по БЭМ

### ISSUE THREAD

**Issue by igosheva** [Yonmay/Yonmay.github.io#5]
https://github.com/Yonmay/Yonmay.github.io/blob/89ed0f6bb03e5d8648dcce2604f1ab271088c0be/index.html#L20

**Comment by igosheva** [comment]
Через "_" добавляется модификатор, а элементы именуются через "__"

**Comment by igosheva** [comment]
Соответственно у всех li именах ошибки. И всех li в этом списке нужно задать один класс.

**Comment by igosheva** [comment]
Внутри у всех элементов тоже ошибки в именах. Должно быть например вот так:
https://jsfiddle.net/Lgv87gt9/

**Comment by Yonmay** [comment]
понял в чем ошибка, главное это теперь запомнить))
