### ISSUE TITLE
Ошибка в нейминге по БЭМ

### ISSUE THREAD

**Issue by igosheva** [Yonmay/Yonmay.github.io#6]
https://github.com/Yonmay/Yonmay.github.io/blob/89ed0f6bb03e5d8648dcce2604f1ab271088c0be/index.html#L43

**Comment by igosheva** [comment]
Через "_" добавляется модификатор, а элементы именуются через "__". Также все элементы, которые в дальнейшем будут отстилизованы одинакого должны иметь одинаковые классы. В данном случае можно хлебным крошкам добавить просто класс breadcrumbs__link

**Comment by Yonmay** [comment]
тут к каждому диву заданы разные цвета и не смог разобраться как объединить два псевдоэлемента. Чтобы контент вставлялся только перед вторым словом и окрашивалось тоже только второе, а первый чтобы цвет не изменял.

**Comment by igosheva** [comment]
Смотри, главное чтобы класс с модификатором не использовался без основного класса. например в твоем случае просто нужно к breadcrumbs__link_1 добавить breadcrumbs__link и все, ошибки не будет. Класс с модификатором нужен, чтобы выносить туда уникальные стили, а все одинаковые выносишь в базовый класс.
