### ISSUE TITLE
Ошибка в нейминге по БЭМ

### ISSUE THREAD

**Issue by igosheva** [Yonmay/Yonmay.github.io#8]
https://github.com/Yonmay/Yonmay.github.io/blob/89ed0f6bb03e5d8648dcce2604f1ab271088c0be/index.html#L56

**Comment by igosheva** [comment]
Нужно именовать не от предыдущего блока, а от основоного блока, т.е. advantage__meaning, advantage__name и т.д.

**Comment by Yonmay** [comment]
исправил на:

```
<p class="advantage__name">
<p class="advantage__meaning">
```
