### ISSUE TITLE
Все классы именуются в нижнем регистра, никаких классов loftSchool

### ISSUE THREAD

**Issue by igosheva** [Yonmay/Yonmay.github.io#9]
https://github.com/Yonmay/Yonmay.github.io/blob/89ed0f6bb03e5d8648dcce2604f1ab271088c0be/index.html#L109

**Comment by Yonmay** [comment]
так должно быть лучше 
`<div class="footer-left">Сделано с любовью и старанием на курсе «HTML+CSS» в <a href="https://loftschool.com/" class="footer-left__link">LoftSchool</a> Автор работы: <b>Прохладов Вадим</b></div>`

**Comment by igosheva** [comment]
да, верно, отлично))
